name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache: true
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: git fetch --tags --force
      - run: npm ci
      - run: BASE_URL=/barracks/ make build
      - run: mv dist/barracks dist/website/
      - name: Publish Github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/website
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
