name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache: true
      - run: git fetch --tags --force
      - run: make website
      - name: Publish Github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/website
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
