name: test

on:
  push:

jobs:
  test-go:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache: true
      - run: go test ./...
  test-build-website:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make website
